#!/bin/sh

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
tmpfile=$(mktemp /tmp/c2aheui.XXXXXX)

$SCRIPT_DIR/elvm/out/8cc -S -I$SCRIPT_DIR/elvm/libc -o $tmpfile $1

$SCRIPT_DIR/elvm/out/elc -aheui $tmpfile > $1.aheui

rm $tmpfile
